name: Testing Workflow

on:
  issue_comment:
    types: [created]
    
env:
  IMAGE_TAG: PEN-1234_dendd-c05fcb895cf5ace7763c78cf07cd10ec2cbdabab
  MANIFESTS_COMMIT_HASH: dfc9970d6e20f7ff6798d9266058ca69cf688ba0
  
jobs:
  revert-app-repo-commit:
    if: contains(github.event.comment.body, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Split image tag into branch name and commit hash
        run: |
          BRANCH_NAME=$(echo "$IMAGE_TAG" | sed -E 's/-[a-f0-9]{40}$//')
          APP_COMMIT_HASH=$(echo "$IMAGE_TAG" | grep -oE '[a-f0-9]{40}$')
          echo "Branch Name: $BRANCH_NAME"
          echo "Commit Hash: $APP_COMMIT_HASH"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "APP_COMMIT_HASH=$APP_COMMIT_HASH" >> $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: mahira2121/manifests
          ref: main
          token: ${{ secrets.GIT_ACCESS }}

      - name: Revert commit in manifests repository
        run: |
          git revert --no-edit $MANIFESTS_COMMIT_HASH
          git push origin main
