name: Testing Workflow

on:
  pull_request
  
  # repository_dispatch:
  #   types: [deploy_test]
    
env:
  IMAGE_TAG: PEN-1234_dendd-c05fcb895cf5ace7763c78cf07cd10ec2cbdabab
  MANIFESTS_COMMIT_HASH: f2a88d71eeadff46965da30902ab32e730fc4dc4
  
jobs:
  revert-app-repo-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Split image tag into branch name and commit hash
        run: |
          BRANCH_NAME=$(echo "$IMAGE_TAG" | sed -E 's/-[a-f0-9]{40}$//')
          APP_COMMIT_HASH=$(echo "$IMAGE_TAG" | grep -oE '[a-f0-9]{40}$')
          echo "Branch Name: $BRANCH_NAME"
          echo "Commit Hash: $APP_COMMIT_HASH"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "APP_COMMIT_HASH=$APP_COMMIT_HASH" >> $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: mahira2121/manifests
          ref: main
          token: ${{ secrets.GIT_ACCESS }}
          fetch-depth: 0 

      - name: Revert commit in manifests repository
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS }}
        run: |
          git config --global user.email "varshneymahira@gmail.com"
          git config --global user.name "mahira2121"
          git revert --no-edit $MANIFESTS_COMMIT_HASH
          git push origin main



          
